import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Chart from "../components/Chart";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  const [activeTab, changeActiveTab] = useState("cases");

  let sortedData = data
    .map((item) => {
      let displayValue;
      switch (activeTab) {
        case "cases":
          displayValue = item.todayConfirmed;
          break;
        case "cases-per":
          displayValue = (100000 * item.todayConfirmed) / item.population;
          break;
        case "deaths":
          displayValue = item.todayDeaths;
          break;
        case "deaths-per":
          displayValue = (100000 * item.todayDeaths) / item.population;
          break;
      }
      return Object.assign({ displayValue }, item);
    })
    .sort((item1, item2) => item2.displayValue - item1.displayValue);

  return (
    <div className={styles.container}>
      <Head>
        <title>Covid Country Ranking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header changeActiveTab={changeActiveTab} activeTab={activeTab} />

        <Chart data={sortedData} activeTab={activeTab} />
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const response = await fetch("https://corona-api.com/countries").then((res) =>
    res.json()
  );

  let data = response.data
    .filter((item) => item.today && item.population)
    .map((item) => {
      return {
        country: item.name,
        population: item.population,
        todayConfirmed: item.today.confirmed,
        todayDeaths: item.today.deaths,
      };
    });

  return {
    props: { data }, // will be passed to the page component as props
  };
}
